const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Plugins.googleplay,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.TextBox,
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Cnds.IsVisible
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{simplicio: 0},
	{Mouse: 0},
	{Toque: 0},
	{Cano: 0},
	{cano2: 0},
	{Texto: 0},
	{ceu: 0},
	{Vídeo: 0},
	{voando: 0},
	{Sprite: 0},
	{GooglePlay: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Logo: 0},
	{Informacoes: 0},
	{rank: 0},
	{GameScore: 0},
	{tag: 0},
	{botao: 0},
	{EntradaDeTexto: 0},
	{GamePushChannels: 0},
	{start: 0},
	{ponto: 0},
	{m_pontuacao: 0},
	{jogar: 0},
	{m_jogar: 0},
	{pontos: 0},
	{pontos2: 0}
];

self.InstanceType = {
	simplicio: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Cano: class extends self.ISpriteInstance {},
	cano2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	ceu: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	voando: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GooglePlay: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Informacoes: class extends self.ITextInstance {},
	rank: class extends self.ITextInstance {},
	GameScore: class extends self.IInstance {},
	botao: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	GamePushChannels: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	m_pontuacao: class extends self.ISpriteInstance {},
	m_jogar: class extends self.ISpriteInstance {}
}